### ISSUE TITLE
what warn

### ISSUE THREAD

**Issue by blackvccat** [jenchanws/create-track-map#24]
19:36:13] [TrackMap watcher/WARN] [createtrackmap/]: Exception during update loop

**Comment by jenchanws** [comment]
Duplicate of #21. I already know about this issue; just give me a bit to write a fix.

**Comment by blackvccat** [comment]
very nice 謝謝



---Original---
From: "Jennifer Chan ***@***.***&gt;
Date: Tue, Apr 25, 2023 04:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jenchanws/create-track-map] what warn (Issue #24)




 
Closed #24 as not planned.
