### ISSUE TITLE
Incompatibility with Create 0.5.1a Update

### ISSUE THREAD

**Issue by 2aphids** [jenchanws/create-track-map#30]
Just a heads up - pretty much every other addon has been broken due to the update too.

![image](https://github.com/jenchanws/create-track-map/assets/45242698/ebef3c11-5b39-4929-863b-3979c3396e6e)

**Comment by jenchanws** [comment]
Yeah, literally every addon is broken, I'm *painfully* aware. I'm gonna update it; I just haven't gotten around to it yet. Please be patient.

**Comment by 2aphids** [comment]
Thanks :-)
