### ISSUE TITLE
No reserved blocks or yellow signals

### ISSUE THREAD

**Issue by Zhincore** [jenchanws/create-track-map#36]
Hello,
I've noticed I have never seen my map show reserved rail block nor yellow signal.

I would assume these features got lost during 0.5.1 migration or maybe my network is not using these features?

Thank you,
otherwise this mod is a great addition to Create!

**Comment by jenchanws** [comment]
Depends on what your track network looks like. Yellow signals and reserved blocks only happen when you have chain signals (the ones with brass corners, available in base Create); otherwise, regular signals only show either free or occupied.
