### ISSUE TITLE
java.lang.NoSuchFieldError: RAILWAYS

### ISSUE THREAD

**Issue by brenthoes1** [jenchanws/create-track-map#48]

**Comment by brenthoes1** [comment]
Fixed

**Comment by FOREVEREALIZE** [comment]
@brenthoes1 
How did you fix it?

**Comment by brenthoes1** [comment]
@FOREVEREALIZE I was being stupid, used the 0.5.0 jar file instead of 0.5.1 🫠

**Comment by FOREVEREALIZE** [comment]
I just understood why people say GDevs' Ferium should be pre-production...
