### ISSUE TITLE
trains do not show up on the map

### ISSUE THREAD

**Issue by randomperson247365** [jenchanws/create-track-map#49]
the trains do not show up on the track and only sometimes appear in the sidebar for the trains it allows me to go to there location on the map but they are completely invisible on the map idk if this is user error or a bug but I think it's a bug and I have no idea whats causing it

**Comment by randomperson247365** [comment]
this is on the forge version by the way

**Comment by enbyv** [comment]
Please reopen according to the bug report template

**Comment by randomperson247365** [comment]
figured out the issue there was too many chunks in the world
