### ISSUE TITLE
Hello please could you make it for aternos? It's the only free server hosting i can work with. 😢 

### ISSUE THREAD

**Issue by BubacekMisa** [jenchanws/create-track-map#51]

**Comment by enbyv** [comment]
No, it's not possible because of the way Aternos works. There is literally nothing about the mod that could be changed to make it work.

**Comment by BubacekMisa** [comment]
Then why is it in aternos it self

**Comment by randomperson247365** [comment]
> Then why is it in aternos it self

because aternos automatically adds mods when mods get popular enough.
