### ISSUE TITLE
Crash when entering a existing world

### ISSUE THREAD

**Issue by liangmoe** [jenchanws/create-track-map#60]
### Describe the Bug

Select a world and join, the game crash immediately

### Reproduction Steps

1.open minecraft
2.choose a existing world
3.join
...crash

### Expected Result

should be joining the world flawlessly?

### Screenshots and Videos

https://github.com/jenchanws/create-track-map/assets/135343248/4cdcd36c-fdf6-40ad-98db-9e021f2d9990

### Crash Report or Log

Crash report: https://mclo.gs/ejTxCfg

### Operating System

Windows 10

### CTM Version

1.4

### Create Version

0.5.1e

### Minecraft Version

1.20.1

### Mod Loader

Forge

### Modloader Version

47.2.19

### Instance Type

Singleplayer

### Other Mods

	- accurateblockplacement 1.2.1
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.0.0-neoforge
	- aether_emissivity 1.20.1-1.0.0-neoforge
	- aether_enhanced_extinguishing 1.20.1-1.0.0-neoforge
	- aether_redux 1.20.1
	- ambientsounds 5.3.5
	- amecsapi 1.5.3+mc1.20-pre1
	- ancient_aether 0.8.3
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.1.12
	- armortrimitemfix 1.0.2
	- asynclocator 1.3.0
	- authme 7.0.21.20
	- barteringstation 8.0.0
	- bclib 3.0.14
	- bellsandwhistles 0.4.3-1.20.x
	- better_trim_tooltips 1.0.1
	- betteradvancements 0.3.2.162
	- betterclouds 1.3.131.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterend 4.0.11
	- betterendisland 1.20-Forge-2.0.4
	- betterf3 7.0.2
	- betterfortresses 1.20-Forge-2.0.5
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betternether 9.0.10
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterpingdisplay 1.1
	- betterstats 3.7fabric-1.20.1
	- betterstrongholds 1.20-Forge-4.0.3
	- betterthirdperson 1.9.0
	- bettertridents 8.0.1
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomeinfo 1.5
	- blanket_client_tweaks 1.1.4
	- blue_endless_jankson 1.2.2
	- blur 3.1.1
	- bobby 5.0.1
	- bookshelf 20.1.8
	- borderlessmining 1.1.81.20.1
	- bosses_of_mass_destruction 1.7.5-1.20.1
	- cardinal_components 5.2.2
	- cardinal_components_base 5.2.2
	- cardinal_components_block 5.2.2
	- cardinal_components_chunk 5.2.2
	- cardinal_components_entity 5.2.2
	- cardinal_components_item 5.2.2
	- cardinal_components_level 5.2.2
	- cardinal_components_scoreboard 5.2.2
	- cardinal_components_world 5.2.2
	- cataclysm 1.0
	- chat_heads 0.10.30
	- chatpatches 201.5.5
	- chefsdelight 1.0.3-forge-1.20.1
	- chunky 1.3.92
	- citadel 2.4.9
	- clean_tooltips 1.0
	- clickthrough 1.20-fabric0.83.0-0.4.1
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- com_github_jdiemke_delaunay_triangulator_delaunaytriangulator 1.0.0
	- com_github_llamalad7_mixinextras 0.2.0-rc.5
	- com_typesafe_config 1.4.2
	- connectorextras 1.9.0+1.20.1
	- connectorextras_architectury_bridge 1.9.0+1.20.1
	- connectorextras_continuity_compat 1.9.0+1.20.1
	- connectorextras_emi_bridge 1.9.0+1.20.1
	- connectorextras_energy_bridge 1.9.0+1.20.1
	- connectorextras_geckolib_fabric_compat 1.9.0+1.20.1
	- connectorextras_jei_bridge 1.9.0+1.20.1
	- connectorextras_kubejs_bridge 1.9.0+1.20.1
	- connectorextras_modmenu_bridge 1.9.0+1.20.1
	- connectorextras_rei_bridge 1.9.0+1.20.1
	- connectorextras_terrablender_bridge 1.9.0+1.20.1
	- connectormod 1.0.0-beta.32+1.20.1
	- continue_nojpms 1.2.21.20
	- continuity 3.0.0-beta.41.20.1
	- craftpresence 2.2.6
	- create 0.5.1.f
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.h
	- create_jetpack 4.2.0
	- create_sa 2.0.4.
	- create_structures 0.1.1
	- createoreexcavation 1.4.2
	- createtrackmap 1.4
	- creativecore 2.11.18
	- crowdin_translate 1.41.19.3
	- ctov 3.3.6
	- culllessleaves 1.20.1-1.0.5
	- cumulus_menus 1.20.1-1.0.0-neoforge
	- curios 5.3.5+1.20.1
	- custom_crosshair_mod 1.5.4-forge
	- deep_aether 1.20.1-1.0.13.1
	- detailab 2.6.31.20.1-fabric
	- ding 1.4.1
	- dragonmounts 1.1.5.b3
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- eatinganimationid 1.201.9.5
	- elytra_physics 2.0
	- embeddium 0.2.16+mc1.20.1
	- emojitype 2.2.3+1.20.4
	- enchdesc 17.0.11
	- ends_delight 1.0.1
	- entity_model_features 1.2.1
	- entity_texture_features 5.1.2
	- entityculling 1.6.2
	- euphoria_patcher 0.2.0-forge
	- fabric_api 0.91.0+1.10.4+1.20.1
	- fabric_api_base 0.4.30+ef105b4977
	- fabric_api_lookup_api_v1 1.6.35+67f9824077
	- fabric_biome_api_v1 13.0.12+dd0389a577
	- fabric_block_api_v1 1.0.10+0e6cb7f777
	- fabric_block_view_api_v2 1.0.0+0767707077
	- fabric_blockrenderlayer_v1 1.1.40+1d0da21e77
	- fabric_client_tags_api_v1 1.1.1+5d6761b877
	- fabric_command_api_v1 1.2.33+f71b366f77
	- fabric_command_api_v2 2.2.12+561530ec77
	- fabric_content_registries_v0 4.0.10+a670df1e77
	- fabric_convention_tags_v1 1.5.4+fa3d1c0177
	- fabric_data_generation_api_v1 12.3.3+369cb3a477
	- fabric_dimensions_v1 2.1.53+8005d10d77
	- fabric_entity_events_v1 1.5.22+b909fbe377
	- fabric_events_interaction_v0 0.6.1+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.39+461110ab77
	- fabric_item_api_v1 2.1.27+2272fc7f77
	- fabric_item_group_api_v1 4.0.11+9801bf5177
	- fabric_key_binding_api_v1 1.0.36+561530ec77
	- fabric_language_kotlin 1.10.17kotlin.1.9.22
	- fabric_lifecycle_events_v1 2.2.21+afab492177
	- fabric_loot_api_v2 1.2.0+eb28f93e77
	- fabric_message_api_v1 5.1.8+52cc178c77
	- fabric_mining_level_api_v1 2.1.49+561530ec77
	- fabric_model_loading_api_v1 1.0.2+142e25ab77
	- fabric_models_v0 0.4.1+7c3892a477
	- fabric_networking_api_v1 1.3.10+503a202477
	- fabric_object_builder_api_v1 11.1.2+2174fc8477
	- fabric_particles_v1 1.1.1+78e1ecb877
	- fabric_recipe_api_v1 1.0.20+514a076577
	- fabric_registry_sync_v0 2.3.2+1c0ea72177
	- fabric_renderer_api_v1 3.2.0+1d29b44577
	- fabric_renderer_indigo 1.5.0+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.36+a6081afc77
	- fabric_rendering_fluids_v1 3.0.27+4ac5e37a77
	- fabric_rendering_v1 3.0.7+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.7+9ad825cd77
	- fabric_resource_loader_v0 0.11.9+142e25ab77
	- fabric_screen_api_v1 2.0.7+45a670a577
	- fabric_screen_handler_api_v1 1.3.29+561530ec77
	- fabric_sound_api_v1 1.0.12+4f23bd8477
	- fabric_transfer_api_v1 3.3.3+b00938ec77
	- fabric_transitive_access_wideners_v1 4.3.0+1880499877
	- fallingleaves 2.1.0
	- farmersdelight 1.20.1-1.2.3
	- fastipping 1.0.1
	- fastload 3.4.0
	- fastquit 3.0.01.20
	- fastrandom 1.6.0
	- ferritecore 6.0.1
	- flightlib 2.0.3
	- flywheel 0.6.10-7
	- foglooksmodernnow 1.2.1
	- foodeffecttooltips 1.0.0
	- forge 47.2.19
	- forgeconfigapiport 8.0.0
	- fpsreducer 1.20-2.5
	- freecam 1.2.1+1.20
	- fullscreeno 1.0.0
	- functionalstorage 1.20.1-1.2.7
	- gbfabrictools 1.41.20
	- geckolib 4.3.1
	- gravestone 1.20.1-1.0.12
	- highlighter 1.1.9
	- iceberg 1.1.18
	- immediatelyfast 1.2.8+1.20.4
	- interiors 0.5.2
	- inventoryprofilesnext 1.10.9
	- io_leangen_geantyref_geantyref 1.3.13
	- iris 1.6.9
	- irisflw 1.20.1-0.2.0
	- itemphysiclite 1.6.1
	- jade 11.7.1
	- jei 15.9999
	- kirin 1.15.41.20
	- kotlinforforge 4.10.0
	- lambdynlights 2.3.21.20.1
	- languagereload 1.5.101.20.1
	- lazurite 1.0.1+mc1.20.1
	- leavemybarsalone 8.0.0
	- legendarytooltips 1.4.5
	- libipn 4.0.1
	- lootr 0.7.29.68
	- lost_aether_content 1.2.3
	- maelstrom_library 1.6.1-1.20
	- memoryleakfix 1.1.4
	- minecells 1.6.1
	- minecraft 1.20.1
	- miners_delight 1.20.1-1.2.1
	- mixinextras 0.2.0-beta.9
	- modernfix 5.11.1+mc1.20.1
	- modmenu 7.2.2
	- mr_ctov_chefsdelightcompat 2.0
	- mr_ctov_createstructures 1.0
	- mr_ctov_farmersdelightcompat 2.1
	- mr_village_nullifier 2.0.0
	- mr_village_nullifierterralith 1.0.1
	- multipart_entities 1.5-1.20
	- mutantmonsters 8.0.6
	- nethersdelight 1.20.1-4.0
	- nitrogen_internals 1.20.1-1.0.1-neoforge
	- no_telemetry 1.8.0
	- nochatreports 1.20.1-v2.2.2
	- noshade 1.0.2
	- notenoughanimations 1.7.0
	- oceansdelight 1.0.2-1.20
	- oculus 1.6.9
	- omega_config 1.2.3-1.18.1
	- org_jetbrains_kotlin_kotlin_reflect 1.9.22
	- org_jetbrains_kotlin_kotlin_stdlib 1.9.22
	- org_jetbrains_kotlin_kotlin_stdlib_jdk7 1.9.22
	- org_jetbrains_kotlin_kotlin_stdlib_jdk8 1.9.22
	- org_jetbrains_kotlinx_atomicfu_jvm 0.23.1
	- org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm 1.7.3
	- org_jetbrains_kotlinx_kotlinx_coroutines_jdk8 1.7.3
	- org_jetbrains_kotlinx_kotlinx_datetime_jvm 0.5.0
	- org_jetbrains_kotlinx_kotlinx_serialization_cbor_jvm 1.6.2
	- org_jetbrains_kotlinx_kotlinx_serialization_core_jvm 1.6.2
	- org_jetbrains_kotlinx_kotlinx_serialization_json_jvm 1.6.2
	- org_spongepowered_configurate_core 4.1.2
	- org_spongepowered_configurate_hocon 4.1.2
	- owo 0.11.21.20
	- packetfixer 1.2.1
	- panorama_screens 1.0+forge+mc1.20
	- particlerain 2.0.8
	- particletweaks 1.1.3-Fabric1.20.1-unstable
	- patchouli 1.20.1-84-FORGE
	- paxi 1.20-Forge-4.0
	- pingwheel 1.7.1
	- playeranimator 1.0.2-rc1+1.20
	- presencefootsteps 1.9.1
	- pride 1.2.01.19.4
	- prism 1.0.5
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.12
	- quick_hotkeys 1.0.2
	- radium 0.12.2+git.5f80f74
	- railways 1.5.3+forge-mc1.20.1
	- reach_entity_attributes 2.4.0
	- reeses_sodium_options 1.0.4
	- rei_plugin_compatibilities 12.0.93
	- resourcepackoverrides 8.0.2
	- roughlyenoughitems 12.0.684
	- roughlyenoughprofessions 2.0.2
	- rrls 3.2.0-1.20.1-forge
	- rubidium 0.7.1
	- rubidium_extra 0.5.3.1+mc1.20.1-build.110
	- satin 1.20.1+1.15.0-SNAPSHOT
	- screenshotclipboard 1.0.9
	- shulkerboxtooltip 4.0.4+1.20.1
	- skinlayers3d 1.6.1
	- sliceanddice 3.2.0
	- smoothboot 0.0.3
	- smoothmenu 1.1.0
	- sound_physics_remastered 1.20.1-1.3.1
	- soundcontroller 1.0.0
	- spark 1.10.53
	- spruceui 5.0.01.20
	- starlight 1.1.2+forge.1cda73c
	- structure_gel 2.16.0
	- stylisheffects 8.0.0
	- tcdcommons 3.7fabric-1.20.1
	- tectonic 2.1.1
	- terrablender 3.0.1.2
	- terralith 2.4.11
	- textrues_embeddium_options 0.1.3+mc1.20.1
	- titanium 3.8.25
	- toolstats 16.0.7
	- tradingpost 8.0.1
	- travelersbackpack 9.1.12
	- travelerstitles 1.20-Forge-4.0.1
	- vanillafix 1.0.0-forge-beta
	- visuality 2.0.2
	- visualworkbench 8.0.0
	- vmp 0.2.0+beta.7.101
	- voicechat 1.20.1-2.4.32
	- wakes 0.2.2
	- waveycapes 1.3.2
	- wi_zoom 1.5-MC1.20.1-Forge
	- witherstormmod 4.0.1.1
	- wits 1.1.0+1.20.1-forge
	- wunderlib 1.1.5
	- xaerominimap 23.9.3
	- xaeroplus 1.20.1
	- xaeroworldmap 1.37.2
	- xaerozoomout 1.1.0
	- yet_another_config_lib_v3 3.2.1+1.20
	- yungsapi 1.20-Forge-4.0.2
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3

### Additional Context

note: create version is 0.5.1.f, which isnt have that option in this page, not sure if its causing the bug

**Comment by enbyv** [comment]
> Caused by: java.net.BindException: Address already in use: bind
What port do you have CTM configured to use and is anything else already using it?

**Comment by liangmoe** [comment]
I letting configured file just default, how do i check if there is anything else that used CTM port?

**Comment by liangmoe** [comment]
Closing this since i cant reproduce this again by myself, it just work for me now, love the mod!
